# Generated by Django 2.1.4 on 2019-01-04 09:34

from django.db import migrations
import prose.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=prose.fields.DocumentContentField(),
        ),
    ]
