# Generated by Django 2.1.4 on 2019-01-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prose.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prose', '0002_auto_20190104_0934'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content', prose.fields.DocumentField(on_delete=django.db.models.deletion.CASCADE, to='prose.Document')),
            ],
        ),
    ]
