# Generated by Django 4.1.7 on 2023-03-16 10:08

from django.db import migrations
import prose.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_content_article_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
