name: Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry==1.3.2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: poetry
    - run: poetry install
    - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - run: poetry publish --build
